name: build hugo

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83.1'

      - name: Build
        run: hugo --minify
      
      - name: Upload as Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: rendered-html
          path: ./public
